### ISSUE TITLE
Make/ensure ClimMob complies with GDPR

### ISSUE THREAD

**Issue by qlands** [mrbotcr/py3ClimMob#241]
We need to check policy changes and processes for GDPR int the context that users own the data.

**Comment by kauedesousa** [comment]
Part of this is also discussed here https://github.com/BioversityCostaRica/py3ClimMob/issues/124

**Comment by MarManrow** [comment]
Closed because it is duplicated. All information regarding this issue is in issue https://github.com/mrbotcr/py3ClimMob/issues/124.
